# Reusable workflow for Android build steps
name: Android Build Common

on:
  workflow_call:
    inputs:
      build_apk:
        required: false
        type: boolean
        default: true
      build_aab:
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: 'stable'
          version: 'latest'
          cache: true
          cache-sdk: true
      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - name: Install dependencies
        run: flutter pub get
      - name: Decode Keystore
        if: ${{ inputs.build_apk || inputs.build_aab }}
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > android/keystore.p12
          echo "storePassword=$KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "storeFile=$(realpath android/keystore.p12)" >> android/key.properties
          echo "storeType=PKCS12" >> android/key.properties
      - name: Build appbundle
        if: ${{ inputs.build_aab }}
        run: flutter build appbundle
      - name: Build apk
        if: ${{ inputs.build_apk }}
        run: flutter build apk --split-per-abi
      - name: Upload appbundle
        if: ${{ inputs.build_aab }}
        uses: actions/upload-artifact@v4
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/*.aab
          retention-days: 1
      - name: Upload apk
        if: ${{ inputs.build_apk }}
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/apk/release/*.apk
          retention-days: 1
