name: Apps Android Build

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build-apps:
    uses: ./.github/workflows/android-common.yaml
    with:
      build_apk: true
      build_aab: true