name: Apps Android Publish

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-apps:
    uses: ./.github/workflows/android-common.yaml
    with:
      build_apk: false
      build_aab: true
    secrets:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

  publish-and-bump:
    needs: build-apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download appbundle artifact
        uses: actions/download-artifact@v4
        with:
          name: appbundle

      - name: List files after artifact download
        run: |
          pwd
          ls -R

      - name: Move .aab to expected location
        run: |
          mkdir -p build/app/outputs/bundle/release
          find . -name "*.aab" -exec cp {} build/app/outputs/bundle/release/app-release.aab \;
          ls -l build/app/outputs/bundle/release

      - name: Get App ID from build.gradle.kts
        id: app_id
        run: |
          app_id=$(cat android/app/build.gradle.kts | grep "applicationId" | cut -d'"' -f2)
          echo "APP_NAMESPACE=$app_id" >> $GITHUB_ENV

      - name: Publish appbundle to Play Store
        id: publish
        uses: KevinRohn/github-action-upload-play-store@v1.0.1
        with:
          service_account_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          package_name: ${{ env.APP_NAMESPACE }}
          aab_file_path: build/app/outputs/bundle/release/app-release.aab
          track: internal
          release_status: draft

      - name: Bump version in pubspec.yaml
        if: success()
        shell: bash
        run: |
          current_version=$(grep '^version:' pubspec.yaml | cut -d' ' -f2)
          base_version=$(echo $current_version | cut -d'+' -f1)
          build_number=$(echo $current_version | cut -d'+' -f2)
          if [ -z "$build_number" ]; then build_number=0; fi
          new_build_number=$((build_number + 5))
          new_version="${base_version}+${new_build_number}"
          sed -i "s/^version: .*/version: $new_version/" pubspec.yaml
          echo "Bumped version to $new_version"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Commit and push version bump
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pubspec.yaml
          git commit -m "chore: bump version to $NEW_VERSION for Play Store"
          git push
