name: Apps Android Publish

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-apps:
    uses: ./.github/workflows/android-common.yaml
    with:
      build_apk: false
      build_aab: true

  publish:
    needs: build-apps
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download appbundle artifact
        uses: actions/download-artifact@v4
        with:
          name: appbundle
      - name: Get App ID from build.gradle.kts
        id: app_id
        run: |
          app_id=$(cat android/app/build.gradle.kts | grep "applicationId" | cut -d'"' -f2)
          echo "APP_NAMESPACE=$app_id" >> $GITHUB_ENV
      - name: Publish appbundle to Play Store
        uses: KevinRohn/github-action-upload-play-store@v1.0.1
        with:
          service_account_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          package_name: ${{ env.APP_NAMESPACE }}
          aab_file_path: build/app/outputs/bundle/release/app-release.aab
          track: internal
          release_status: draft
