name: Apps Android Build

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build-apps:
    uses: ./.github/workflows/android-common.yaml
    with:
      build_apk: true
      build_aab: true
    secrets:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}