name: Bump pubspec version for Play Store

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump version in pubspec.yaml (+5)
        shell: bash
        run: |
          current_version=$(grep '^version:' pubspec.yaml | cut -d' ' -f2)
          base_version=$(echo $current_version | cut -d'+' -f1)
          build_number=$(echo $current_version | cut -d'+' -f2)
          if [ -z "$build_number" ]; then build_number=0; fi
          new_build_number=$((build_number + 5))
          new_version="${base_version}+${new_build_number}"
          sed -i "s/^version: .*/version: $new_version/" pubspec.yaml
          echo "Bumped version to $new_version"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pubspec.yaml
          git commit -m "chore: bump version to $new_version for Play Store"
          git push
